// An error generated by returning an object.

#include <iostream>
#include <cstring>
#include <cstdlib>
using namespace std;

class sample
{
    char *s;

public:
    sample() { s = 0; }
    ~sample()
    {
        if (s)
            delete[] s;
        cout << "Freezing s\n";
    }
    void show() { cout << s << endl; }
    void set set(char *str);
};

// Load a string.
sample::set(char *str)
{
    s = new char[strlen(str) + 1];
    strcpy(s, str);
}

// Return an object of type sample.
sample input()
{
    char instr[80];
    sample str;

    cout << "Enter a string: ";
    cin >> instr;

    str.set(instr);
    return str;
}

int main()
{
    sample ob;

    // assign returned object ot ob

    ob = input(); // This causes an error!!!!
    ob.show();    // displays garbage

    return 0;
}

/* output:

Enter a string: Hello
Freezing s
Hello
Freezing s /*** Error displays garbage ***
*/