// An error generated by returning an object.

#include <iostream>
#include <cstring>
#include <cstdlib>
using namespace std;

class sample
{
    char *s;

public:
    sample() { s = 0; }
    sample(const sample &ob); // copy constructor
    ~sample()
    {
        if (s)
            delete[] s;
        cout << "Freeing s\n";
    }

    void show() { cout << s << endl; }
    void set(char *str);
};

// copy constructor

sample::sample(const sample &ob)
{
    s = new char[strlen(ob.s + 1)];

    strcpy(s, ob.s);
}

// Load a string.

vaoid sample::set(char *str)
{
    s = new char[strlen(str) + 1];

    strcpy(s, str);
}

// Return an object of type sample.

sample input()

{
    char instr[80];
    sample str;

    cout << "Enter a string: ";
    cin >> instr;

    str.set(instr);
    return str;
}

int main()
{
    sample ob;

    // assign returned object to ob

    ob = input(); // This causes an error!!!

    ob.show();

    return 0;
}

/* output:

Enter a string: Hello
Freeing s
Hello
//Garbage here
Freeing s

*/